In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("../data/raw_data.csv")

/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (1,2,5,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
X = df.drop(["C_YEAR", "C_VEHS", "C_CONF", "V_ID",
             "P_ID", "P_PSN", "P_ISEV", "P_USER", 
             "C_CASE", "C_SEV", "P_SEX", "P_SAFE", "P_AGE", "V_YEAR"], axis=1)

y = df["C_SEV"]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=407)
combined_train = pd.concat([X_train, y_train], axis=1)

In [8]:
drop_strings = ((combined_train.C_MNTH != "UU")& 
         (combined_train.C_WDAY != "U")  & 
         (combined_train.C_HOUR != "UU") & 
         (combined_train.C_RCFG != "UU") & 
         (combined_train.C_RCFG != "QQ") & 
         (combined_train.C_WTHR != "U") & 
         (combined_train.C_WTHR != "Q") &
         (combined_train.C_RSUR != "Q") &
         (combined_train.C_RSUR != "U") &
         (combined_train.C_RALN != "Q") &
         (combined_train.C_RALN != "U") &
         (combined_train.C_TRAF != "QQ") &
         (combined_train.C_TRAF != "UU") &
         (combined_train.V_TYPE != "NN") & 
         (combined_train.V_TYPE != "UU") & 
         (combined_train.V_TYPE != "QQ"))

In [9]:
clean = combined_train[drop_strings]
clean.apply(pd.to_numeric);

In [10]:
final_clean = pd.get_dummies(clean)

In [11]:
df = final_clean[set(final_clean.columns)]

In [12]:
df

,C_HOUR_15,C_RSUR_1,C_MNTH_10,C_TRAF_16,C_HOUR_22,C_HOUR_05,C_MNTH_11,C_MNTH_11,C_TRAF_04,C_RCFG_04,...,C_HOUR_13,C_HOUR_18,C_MNTH_5,C_MNTH_12,C_MNTH_3,V_TYPE_20,C_RCFG_10,C_HOUR_10,C_RCFG_05,C_RCFG_02
165385,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
86308,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
239620,0,1,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
233305,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
268986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103603,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
241757,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
127224,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
171991,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
138098,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df.to_csv("cleaned.csv")